-- V1__create_schema.sql
-- Esquema inicial para encuestas y opciones

CREATE TABLE IF NOT EXISTS encuestas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS opciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  texto_opcion VARCHAR(255) NOT NULL,
  contador_votos BIGINT DEFAULT 0,
  encuesta_id BIGINT NOT NULL,
  CONSTRAINT fk_encuesta FOREIGN KEY (encuesta_id) REFERENCES encuestas(id)
);
